Ajax. Part #7
natalya-bogdanova/QnA pull request #4
Opened 2019-11-09 17:37 UTC by natalya-bogdanova

2019-11-11 17:15 UTC, aishek requested changes

2019-11-11 17:15 UTC, aishek commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question), notice: 'You are not authorized for this.'
Для аякса это неактуально

2019-11-11 17:15 UTC, aishek commented on app/controllers/questions_controller.rb
> +      redirect_to question_path(@question), notice: 'You are not authorized for this.'
Для аякса так не нужно делать

2019-11-11 17:15 UTC, aishek commented on app/models/answer.rb
> +  validates_uniqueness_of :question_id, if: :validate_uniqueness_of_accepted_answer
Направление мысли верное, но тут нужно проверить уникальность значения `accepted` только если оно установлено в `true` в рамках одного и того же `question_id`. Ну и сюда же задание со звёздочкой: добавить индекс в базу для этого.

2019-11-11 17:15 UTC, aishek commented on app/models/answer.rb
> +    self.update!(accepted: true)
И обернуть в транзакцию обязательно

2019-11-11 17:15 UTC, aishek commented on app/models/answer.rb
> +  default_scope { order(accepted: :desc) }
А в каком порядке остальные выводить?

2019-11-11 17:15 UTC, aishek commented on app/views/answers/_answer.html.slim
> +    -if current_user&.author?(answer) && answer.persisted?
Проверки на `answer.persisted?` быть не должно. Лучше на уровне контроллера ассоциацию расцепить.

2019-11-11 17:15 UTC, aishek commented on app/views/questions/update.js.erb
> +<% if !@question.errors.present? %>
Логику лучше "выпрямить" с помощью `@question.errors.blank?`

2019-11-11 17:15 UTC, aishek commented on app/views/questions/update.js.erb
> +$('.question' + ' p').text('<%= @question.body %>');
Странные конструкции

2019-11-11 17:15 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        end.to_not change(answer, :body)
Без перезагрузки ответа из базы проверка на самом деле не работает

2019-11-11 17:15 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        end.to_not change(answer, :body)
Без перезагрузки ответа из базы проверка на самом деле не работает

2019-11-11 17:15 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +        end.to_not change(answer, :body)
Без перезагрузки ответа из базы проверка на самом деле не работает

2019-11-11 17:15 UTC, aishek commented on spec/models/answer_spec.rb
> +  context 'method accept!' do
Подобные контексты принято называть `context '#accept!'`, а если описывается метод класса, то `context '.accept!'`.

2019-11-11 17:15 UTC, aishek commented on spec/features/question/accept_answer_spec.rb
> +   accepted_answer
Вот это нужно заменить на `let!`

2019-11-11 17:15 UTC, aishek commented on spec/features/question/accept_answer_spec.rb
> +   sign_in(author)
Просится в предусловия. Хотя если можно без этого действия, то надо обойтись без него

2019-11-11 20:19 UTC, natalya-bogdanova commented on app/views/questions/update.js.erb
> +$('.question' + ' p').text('<%= @question.body %>');
чуть поправила, такая уж верстка у меня :)

2019-11-12 09:14 UTC, natalya-bogdanova commented on app/views/answers/_answer.html.slim
> +    -if current_user&.author?(answer) && answer.persisted?
в общем-то, вроде эта проверка в принципе не нужна

2019-11-12 09:44 UTC, aishek requested changes

2019-11-12 09:44 UTC, aishek commented on app/models/answer.rb
> +  default_scope { order(accepted: :desc).order(:created_at) }
Кажись можно вот так `order('accepted DESC, created_at)`

2019-11-12 09:44 UTC, aishek commented on app/models/answer.rb
> +  default_scope { order(accepted: :desc).order(:created_at) }
И для этого тоже нужен юнит-тест

2019-11-13 07:42 UTC, aishek requested changes

2019-11-13 07:42 UTC, aishek commented on app/models/answer.rb
> +  default_scope { order('accepted DESC, created_at') }
Ещё вот сюда нужен юнит-тест: забрать все ответы вопроса и сравнить их с массивом в нужном порядке

2019-11-13 10:46 UTC, aishek approved these changes

2019-11-14 14:02 UTC, merged